defmodule Prog.Factory do
  use ExMachina.Ecto, repo: Prog.Repo

  def post_factory do
    title = sequence(:title, &"Post title #{&1}")

    %Prog.Blog.Post{
      title: title,
      slug: Prog.Slug.to_slug(title),
      body: "A post generated by factory"
    }
  end
end
